---
- name: Пользовать доступы
  hosts: all
  become: true
  tasks:
    - name: Создание пользователя
      user:
        name: brickdev
        password: "{{ 'pass' | password_hash('sha512') }}"
        shell: /bin/bash

    - name: Разрешить авторизацию через ssh по ключу
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
      notify: Перезапуск ssh

    - name: Запретить логин по ssh от пользователя root
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Перезапуск ssh

    - name: Копирование публичного ключа для пользователя brickdev
      authorized_key:
        user: brickdev
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDW1sg+ys6EEZd6ZzbDlrMMybOBUALEtERY2/ZKsvgbcAzTERxbtsqu+iNNDBo+sf3L3YuWkd8fLH4SJ3MQV42ySc6ml2tMT0G2r+QIWwFz+nPaD2DY8blgFpsa41TZxwKgLmqEtUVlps9Q6Un5KtJMjTl2MWYKswdxSqHw8em0DNigJolWfzsmoTvd1HXTYdj/PiJECW3nS38PFlL19Av6ipwrbxme2/VyvjolX5F3p/dgLkuUU7UMQ+tlx9gAlN0F/Tf6zMHSubIBC7lOf58zP+IlykdD4leVaNpFckk9hxnKCZpyM7jlwi2YSnYLAOh4v56NTq7c/yG2jX9+lSb"
        state: present

  handlers:
    - name: Перезапуск ssh
      service:
        name: ssh
        state: restarted
